version: '3'

tasks:
  default:
    cmds:
      - task --list

  client:
    dir: client
    cmds:
      - elm make src/Main.elm --output elm.js
    sources:
      - elm.js
      - src/**/*.elm
    generates:
      - elm.js
  
  server:
    cmds:
      - go build
    sources:
      - main.go
      - server/**/*.go
    generates:
      - bieterrunde

  build:
    deps:
      - client
      - server

  start:
    desc: |
      Starts the server. 
      
        Use --watch to restart the server if the source changes.

        task start --watch

    deps: 
      - build
      - config

    cmds:
    - ./bieterrunde

    sources:
      - config.toml
      - client/index.html

    method: none

    ignore_error: true


  config:
    desc: |
      Creates the config file with default values.

    cmds:
      - go run tools/config/main.go > config.toml

    sources:
    - Taskfile.yml
    
    generates:
      - config.toml

  clean:
    desc: Removes all generated files
    cmds:
      - git clean -xf

  release:
    desc: |
      Creates a new release. 
      
        You manually have to create a git tag and set the
        ENC-variable `GITHUB_TOKEN`.

        git tag v0.1.0
        export GITHUB_TOKEN=12345
    cmds:
      - goreleaser release
      
