version: '3'

tasks:
  default:
    cmds:
      - task --list

  client:
    dir: client
    cmds:
      - elm make src/Main.elm --output elm.js
    sources:
      - elm.js
      - src/**/*.elm
    generates:
      - elm.js
  
  server:
    cmds:
      - go build
    sources:
      - main.go
      - server/**/*.go
    generates:
      - bieterrunde

  build:
    deps:
      - client
      - server

  start:
    desc: |
      Starts the server. 
      
        Use --watch to restart the server if the source changes.

        task start --watch

    deps: 
      - build
      - config

    cmds:
    - ./bieterrunde

    sources:
      - config.toml

    method: none

    ignore_error: true


  config:
    desc: |
      Creates the config file

        Example: task config admin_password="my password"

        Variables:
        - admin_password   (default: admin)
        - listen_addr      (default: :9600)

    vars:
      DEFAULT_ADMIN_PASS: admin
      DEFAULT_LISTEN_ADDR: :9600

    cmds:
      - |
        cat << EOF > config.toml
        admin_password = "{{or .admin_password .DEFAULT_ADMIN_PASS}}"
        listen_addr = "{{or .listen_addr .DEFAULT_LISTEN_ADDR}}"
        EOF

    sources:
    - Taskfile.yml
    
    generates:
      - config.toml

  clean:
    desc: Removes all generated files
    cmds:
      - git clean -xf

  release:
    desc: |
      Creates a new release. 
      
        You manually have to create a git tag and set the
        ENC-variable `GITHUB_TOKEN`.
    cmds:
      - goreleaser release
      
